---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: ((git-repo-name))
  - name: version

outputs:
  - name: output

run:
  path: ((git-repo-name))/concourse/tasks/package/package.sh
  args:
    - ((git-repo-name))
    - output
    - product-blacklist