resources:
  - name: product-blacklist-repo
    type: git
    check_every: 10s
    source:
      uri: https://github.com/JSainsburyPLC/product-blacklist.git
      branch: master

  - name: github-release
    type: github-release
    source:
      owner: JSainsburyPLC
      repository: product-blacklist

jobs:
  - name: build-and-unittest
    public: true
    plan:
      - get: product-blacklist-repo
        trigger: true
      - task: Build Project
        file: product-blacklist-repo/concourse/tasks/package.yml
      - put: github-release
        params:
          name: product-blacklist-jar/product-blacklist-0.0.1-SNAPSHOT.jar
          tag: product-blacklist-repo/target/product-blacklist-0.0.1T.jar
          globs:
            - product-blacklist-repo/target/product-blacklist-0.0.1-SNAPSHOT/product-blacklist-0.0.1-SNAPSHOT.jar
