resources:
  - name: product-blacklist-repo
    type: git
    check_every: 10s
    source:
      uri: https://github.com/JSainsburyPLC/product-blacklist.git
      branch: master
      private_key: {{git-key}}

  - name: test-env
    type: cf
    source:
      api: {{cf-url}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:JSainsburyPLC/golservices-java-devops.git
      branch: master
      file: versions/product-blacklist-version
      private_key: {{git-key}}

jobs:
  - name: increment-version
    plan:
      - get: version
        params: {bump: patch}
      - put: version
        params: {file: version/version}

  - name: build-and-unittest
    public: true
    plan:
      - get: version
        trigger: true
        passed: [increment-version]
      - get: product-blacklist-repo
        timeout: 15s
      - task: Build Project
        file: product-blacklist-repo/concourse/tasks/package.yml
      - put: test-env
        params:
          manifest: product-blacklist-jar/manifest.yml
